### ISSUE TITLE
Need code explanation 

### ISSUE THREAD

**Issue by ammar-khan** [vladyspavlov/html5-canvas-speedometer#1]
You can designed an awesome piece of code 
I would like to understand the code further like:
- How to change the bg color?
- How to add light glowing effects?
- How to change the size of the circles?
Any help will be appreciated 
Thanks

**Comment by vladyspavlov** [comment]
Hi!

> How to change the bg color?

https://github.com/vladyspavlov/html5-canvas-speedometer/blob/2f7ac4b008d04730f775b99f65bbc8c895481266/js/speedometer.js#L918
It's hardcoded for now, but you can edit object or define your own. Maybe i'll refactor this part in the future.

> How to add light glowing effects?

Could you explain what you mean about light glowing effects? Turn lights blink or car lights turned on icon?
Please check this demo, maybe it will be helpful: https://github.com/vladyspavlov/html5-canvas-speedometer/blob/2f7ac4b008d04730f775b99f65bbc8c895481266/js/demo.js#L38

> How to change the size of the circles?

You can change width and height of the canvas to change the size of the whole spedo. But if you need only change the size of the circles look at the constructor of Circle:
https://github.com/vladyspavlov/html5-canvas-speedometer/blob/2f7ac4b008d04730f775b99f65bbc8c895481266/js/speedometer.js#L81
It's also hardcoded for now :(
